- name: variables
  hosts: web
  vars:
    course: "Devops"
    duration: "120"
    from: "siva"
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "I am learning {{course}} from {{from}} and duration is {{duration}} hrs"