- name: variables from files
  hosts: web
  vars_prompt:
  - name: USERNAME
    prompt: enter username
    private: false
  - name: PASSWORD
    prompt: enter password
    private: true
  tasks:
  - name: variables in prompt
    ansible.builtin.debug:
      msg: "Welcome given {{USERNAME}} and {{PASSWORD}} "