- name: condition
  hosts: web
  become: yes
  tasks:
  - name: check id
    ansible.builtin.command: id expense
      register: USERID
      ignore_errors: true
  - name: see the putput
    ansible.builtin.debug:
      msg: "see the output {{USERID}}"